# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: antt1995/dsp-mediawiki
    docker:
      - image: cimg/base:2024.01
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
jobs:
  build:
    parameters:
      mw-version:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image & Publish
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker build ./<< parameters.mw-version >>/apache -t $IMAGE_NAME:<< parameters.mw-version >>
            docker push $IMAGE_NAME:<< parameters.mw-version >>

workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: main
          matrix:
            parameters:
              mw-version: ['1.39', '1.40', '1.41']
          context:
            - DOCKER
