# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: antt1995/dsp-mediawiki
    docker:
      - image: cimg/base:2024.01
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build ./<< parameters.mv-version >>/<< parameters.type >>
      - run:
          name: Archive Docker image
          command: docker save -o << parameters.mv-version >>/<< parameters.type >>/image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./<< parameters.mv-version >>/<< parameters.type >>/image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/<< parameters.mv-version >>/<< parameters.type >>/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
            docker tag $IMAGE_NAME:<< parameters.mv-version >>
            docker push $IMAGE_NAME:<< parameters.mv-version >>
workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: main
          parameters:
            mw-version: ['1.39', '1.40', '1.41']
            type: [apache]
      - publish-latest:
          parameters:
            mv-version: ['1.39', '1.40', '1.41']
            type: [apache]
          requires:
            - build
          filters:
            branches:
              only: main
          context:
            - dockerhub
