name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        type: [apache, fpm, fpm-alpine]
        version: ['1.31', '1.35', '1.36']

    steps:
    - uses: actions/checkout@v1
    - name: v${{ matrix.version }}-${{ matrix.type }}
      run: docker build ./${{ matrix.version }}/${{ matrix.type }}
