name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: v1.31-apache
      run: docker build ./1.31/apache
    - name: v1.31-fpm
      run: docker build ./1.31/fpm
    - name: v1.31-fpm-alpine
      run: docker build ./1.31/fpm-alpine
    - name: v1.34-apache
      run: docker build ./1.34/apache
    - name: v1.34-fpm
      run: docker build ./1.34/fpm
    - name: v1.34-fpm-alpine
      run: docker build ./1.34/fpm-alpine
    - name: v1.35-apache
      run: docker build ./1.35/apache
    - name: v1.35-fpm
      run: docker build ./1.35/fpm
    - name: v1.35-fpm-alpine
      run: docker build ./1.35/fpm-alpine
