name: Update
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    container: debian:bookworm
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Run update
        run: |
          apt-get update && apt-get install --yes --no-install-recommends python3 git gh
          gh repo set-default wikimedia/mediawiki-docker
          git checkout -b auto-update
          ./update.py --commit --pr
